export const Prefix = "APPLICATION_FORM_";

export const ApplicationFormActionType = {
  INSTITUTE_ID: Prefix + "INSTITUTE_ID",
  INSTITUTE_NAME: Prefix + "INSTITUTE_NAME",
  COURSE_ID: Prefix + "COURSE_ID",
  COURSE_NAME: Prefix + "COURSE_NAME",
  FEE_WAIVER_ID: Prefix + "FEE_WAIVER_ID",
  FEE_WAIVER_NAME: Prefix + "FEE_WAIVER_NAME",
  LEVEL_NAME: Prefix + "LEVEL_NAME",
  CATEGORY_NAME: Prefix + "CATEGORY_NAME",

  EMAIL: Prefix + "EMAIL",

  CURRENT_PAGE: Prefix + "CURRENT_PAGE",
  PRE_APP_PAGES: Prefix + "PRE_APP_PAGES",
  INSTITUTE_PAGES: Prefix + "INSTITUTE_PAGES",

  PAGE_NEXT: Prefix + "PAGE_NEXT",
  PAGE_BACK: Prefix + "PAGE_BACK",

  SUBFORM_ADD: Prefix + "SUBFORM_ADD",
  SUBFORM_REMOVE: Prefix + "SUBFORM_REMOVE",
  CONDITION_SUBFORM_ADD: Prefix + "CONDITION_SUBFORM_ADD",
  CONDITION_SUBFORM_REMOVE: Prefix + "CONDITION_SUBFORM_REMOVE",

  FIELD_VALUES: Prefix + "FIELD_VALUES",
  SUBFORM_VALUES: Prefix + "SUBFORM_VALUES",
  CONDITION_VALUES: Prefix + "CONDITION_VALUES",
  CONDITION_SUBFORM_VALUES: Prefix + "CONDITION_SUBFORM_VALUES",
};
